### ISSUE TITLE
Documentación de Arquitectura

### ISSUE THREAD

**Issue by MaGuadalupeQuiroz** [SistemasTecTlaxiaco/documento-de-arquitectura-pc-box#2]
[Documentación de Arquitectura.pdf](https://github.com/SistemasTecTlaxiaco/documento-de-arquitectura-pc-box/files/6361061/Documentacion.de.Arquitectura.pdf)

**Comment by 10154** [comment]
El documento esta bien elaborado y cuneta con todos los requisitos por lo cual tiene un porcentaje de 20%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
